-- CreateEnum
CREATE TYPE "NotificationType" AS ENUM ('GENERAL', 'CLASS_CANCELLED', 'CLASS_RESCHEDULED', 'CLASS_REMINDER', 'ASSIGNMENT', 'ASSIGNMENT_DEADLINE', 'ASSESSMENT_MARK_PUBLISHED', 'RESULT_PUBLISHED', 'PAYMENT_DUE', 'EXAM_SCHEDULE');

-- CreateTable
CREATE TABLE "Notification" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "type" "NotificationType" NOT NULL,
    "title" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "isRead" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Notification_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
